### ISSUE TITLE
`TypeError: 'ToroidalGrid.Reader' object is not callable`

### ISSUE THREAD

**Issue by dschwoerer** [alexrobomind/fusionsc#1]
I tried the example from the documentation, but that does not seem to work with python3.11 or 3.8
```
Python 3.11.3 (main, May 24 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fusionsc as fsc
>>> from fusionsc.devices import w7x
>>> 
>>> grid = w7x.defaultGrid()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'ToroidalGrid.Reader' object is not callable
```

Is the documentation outdated, or is there something wrong with my setup?

**Comment by alexrobomind** [comment]
There is an API inconsistency between the jtext and w7x package. w7x.defaultGrid is a variable holding an immutable description of the grid, while the (newer) jtext package returns a modifiable clone of its recommended grid. Therefore, w7x.defaultGrid is not supposed to be callable. Where in the doc is it used that way?

**Comment by dschwoerer** [comment]
I have it from here:

https://alexrobomind.github.io/fusionsc/setup.html#pre-calculating-fields-for-biot-savart-calculation
